#### Building Frontend Docker Image ####
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend-app:latest',
    './frontend'
  ]

#### Pushing Frontend Docker Image #### Regional
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend-app:latest

#### Building Backend Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend-app:latest', 
    './backend'
  ]

#### Pushing Backend Docker Image #### Regional
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend-app:latest

# Update the Kubernetes manifests for frontend
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://faiza293:$$GIT_ACCESS_TOKEN@github.com/faiza293/gemini-argocd.git -b ${_CD_BRANCH}
    echo "Updating frontend image tag version ..."
    cd Kubernetes
    sed -i "s#IMAGE_PLACEHOLDER#northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend-app:latest#g" frontend-deployment.yaml
    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "faiza mukve"
    git config --global user.email "faizafaazmukve@gmail.com"
    git checkout -b ${_CD_BRANCH} # Ensures branch is correctly set locally
    git add frontend-deployment.yaml
    git commit -m "[Cloud Builder] Updated frontend image tag northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/frontend-app:latest"
    git push https://faiza293:$$GIT_ACCESS_TOKEN@github.com/faiza293/gemini-argocd.git ${_CD_BRANCH}

# Update the Kubernetes manifests for backend
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://faiza293:$$GIT_ACCESS_TOKEN@github.com/faiza293/gemini-argocd.git -b ${_CD_BRANCH}
    echo "Updating backend image tag version ..."
    cd Kubernetes
    sed -i "s#IMAGE_PLACEHOLDER#northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend-app:latest#g" backend-deployment.yaml
    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "faiza mukve"
    git config --global user.email "faizafaazmukve@gmail.com"
    git checkout -b ${_CD_BRANCH} # Ensures branch is correctly set locally
    git add backend-deployment.yaml
    git commit -m "[Cloud Builder] Updated backend image tag northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/backend-app:latest"
    git push https://faiza293:$$GIT_ACCESS_TOKEN@github.com/faiza293/gemini-argocd.git ${_CD_BRANCH}

# Apply Kubernetes manifests to update deployments
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'Kubernetes/frontend-deployment.yaml'
  - '-f'
  - 'Kubernetes/backend-deployment.yaml'

  
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/GIT_ACCESS_TOKEN/versions/latest
    env: 'GIT_ACCESS_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY   # logging
