apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: northamerica-northeast2-docker.pkg.dev/argocd-demo-432200/argo-repo/backend-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/key.json"
        volumeMounts:
        - name: gcp-service-account
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: gcp-service-account
        secret:
          secretName: gcp-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
