apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: northamerica-northeast2-docker.pkg.dev/argocd-demo-432200/argo-repo/backend-app:latest
        ports:
        - containerPort: 8080
        env:
            - name: API_KEY
              value: "AIzaSyCmaL1WQocecWWWWJBbWhfCITq6_Va80Z0"
