apiVersion: v1
kind: Service
metadata:
  name: argoapp-service
  namespace: default
spec:
  selector:
    app: argo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer