apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: default
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: northamerica-northeast2-docker.pkg.dev/argocd-demo-432200/argo-repo/frontend-app:$SHORT_SHA'
        ports:
        - containerPort: 8080
